FROM bellsoft/liberica-openjdk-alpine-musl:11.0.13-8 as builder
WORKDIR /home/app
ARG JAR_FILE=sodata-server/target/sodata.jar
COPY ${JAR_FILE} /home/app/application.jar
RUN java -Djarmode=layertools -jar /home/app/application.jar extract

FROM bellsoft/liberica-openjdk-alpine-musl:11.0.13-8
#FROM eclipse-temurin:17.0.1_12-jre-focal
EXPOSE 8080

WORKDIR /home/app
COPY --from=builder /home/app/dependencies/ ./
COPY --from=builder /home/app/spring-boot-loader/ ./
COPY --from=builder /home/app/snapshot-dependencies/ ./
RUN true 
COPY --from=builder /home/app/application/ ./
RUN chown -R 1001:0 /home/app && \
    chmod -R g=u /home/app
USER 1001
#Log4j 2 CVE-2021-44228
ENV LOG4J_FORMAT_MSG_NO_LOOKUPS=true
ENTRYPOINT ["java" ,"-XX:MaxRAMPercentage=80.0", "-noverify", "-XX:TieredStopAtLevel=1", "org.springframework.boot.loader.JarLauncher", "--spring.config.location=classpath:/application.yml,optional:file:/config/datasets.yml"]

