# ========================
# SERVER
# ========================
server:
  tomcat:
    additional-tld-skip-patterns: '*.jar'
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  forward-headers-strategy: framework

# ========================
# SPRING
# ========================
spring:
  web:
    resources:
        static-locations: classpath:/launcherDir/,classpath:/public/
    #resources:
     #   static-locations: classpath:/launcherDir/,classpath:/public/
    devtools:
        restart:
            additional-exclude: launcherDir/**

management:
    health:
        probes:
            enabled: true
    endpoint:
        health: 
            show-details: always

# ========================
# APPLICATION
# ========================   
logging:
  level:
    org.springframework: ${LOG_LEVEL_SPRING:INFO} 
    ch.so.agi: ${LOG_LEVEL_APP:DEBUG} 

lucene:
    queryMaxRecords: ${LUCENE_QUERY_MAX_RECORDS:500}

app:
    myVar: ${VAR:defaultValue}
    dataBaseUrl: ${DATA_BASE_URL:https://s3.eu-central-1.amazonaws.com/ch.so.agi.geodata/}