app:
    myVar: ${VAR:defaultValue}
    Datasets:
        - id: ch.so.ada.denkmalschutz
          version: current
          owner: mailto:ada@bd.so.ch
          model: SO_ADA_Denkmal_Pub_20211011
          #epsgCode: 2056
          #resolutionScope: 500
          #publishingDate: 2020-08-29
          #lastEditingDate: 2020-08-29
          title: Denkmalschutz
          shortDescription: 
          keywords: Denkmalschutz,Denkmalpflege,ADA
          provider: Amt für Denkmalpflege und Archäologie
          ownerUrl: https://ada.so.ch
          servicer: https://agi.so.ch
          technicalContact: mailto:agi@bd.so.ch
          #furtherInformation: http://geo.so.ch/models/AGI/SO_AGI_AV_GB_Administrative_Einteilungen_Publikation_20180822.uml
          #furtherMetadata: https://www.geocat.ch/geonetwork/srv/ger/md.viewer#/full_view/c899f44f-7c8b-89b5-3c27-617cc9fdfa56
          #knownWMS: 'https://geo.so.ch/api/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.so.agi.av.fixpunkte&STYLES=&SRS=EPSG%3A2056&CRS=EPSG%3A2056&TILED=false&DPI=96&OPACITIES=255&t=633&WIDTH=1544&HEIGHT=907&BBOX=2576618.3333333335%2C1214252.2916666667%2C2658321.6666666665%2C1262247.708333333'
          fileFormats:
            - xtf
            - gpkg
            - shp
            - dxf
        - id: ch.so.afu.abbaustellen
          version: current
          owner: mailto:afu@bd.so.ch
          model: SO_AFU_ABBAUSTELLEN_Publikation_20210630
          #epsgCode: 2056
          #resolutionScope: 500
          #publishingDate: 2020-08-29
          #lastEditingDate: 2020-08-29
          title: Abbaustellen
          shortDescription: 
          keywords: Abbaustellen,AFU
          provider: Amt für Umwelt
          ownerUrl: https://afu.so.ch
          servicer: https://agi.so.ch
          technicalContact: mailto:agi@bd.so.ch
          #furtherInformation: http://geo.so.ch/models/AGI/SO_AGI_AV_GB_Administrative_Einteilungen_Publikation_20180822.uml
          #furtherMetadata: https://www.geocat.ch/geonetwork/srv/ger/md.viewer#/full_view/c899f44f-7c8b-89b5-3c27-617cc9fdfa56
          #knownWMS: 'https://geo.so.ch/api/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.so.agi.av.fixpunkte&STYLES=&SRS=EPSG%3A2056&CRS=EPSG%3A2056&TILED=false&DPI=96&OPACITIES=255&t=633&WIDTH=1544&HEIGHT=907&BBOX=2576618.3333333335%2C1214252.2916666667%2C2658321.6666666665%2C1262247.708333333'
          fileFormats:
            - xtf
            - gpkg
            - shp
            - dxf
        - id: ch.so.afu.baugrundklassen
          version: current
          owner: mailto:afu@bd.so.ch
          model: SO_AFU_Baugrundklassen_Publikation_20201023
          #epsgCode: 2056
          #resolutionScope: 500
          #publishingDate: 2020-08-29
          #lastEditingDate: 2020-08-29
          title: Baugrundklassen nach SIA 261
          shortDescription: 
          keywords: Baugrundklassen,SIA261,AFU
          provider: Amt für Umwelt
          ownerUrl: https://afu.so.ch
          servicer: https://agi.so.ch
          technicalContact: mailto:agi@bd.so.ch
          #furtherInformation: http://geo.so.ch/models/AGI/SO_AGI_AV_GB_Administrative_Einteilungen_Publikation_20180822.uml
          #furtherMetadata: https://www.geocat.ch/geonetwork/srv/ger/md.viewer#/full_view/c899f44f-7c8b-89b5-3c27-617cc9fdfa56
          #knownWMS: 'https://geo.so.ch/api/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.so.agi.av.fixpunkte&STYLES=&SRS=EPSG%3A2056&CRS=EPSG%3A2056&TILED=false&DPI=96&OPACITIES=255&t=633&WIDTH=1544&HEIGHT=907&BBOX=2576618.3333333335%2C1214252.2916666667%2C2658321.6666666665%2C1262247.708333333'
          fileFormats:
            - xtf
            - gpkg
            - shp
            - dxf
        - id: ch.so.afu.bodendaten_nabodat
          version: current
          owner: mailto:afu@bd.so.ch
          model: SO_AFU_Bodenprofilstandorte_Publikation_20210129
          #epsgCode: 2056
          #resolutionScope: 500
          #publishingDate: 2020-08-29
          #lastEditingDate: 2020-08-29
          title: Bodenprofilstandorte
          shortDescription: 
          keywords: Bodenprofilstandorte,AFU
          provider: Amt für Umwelt
          ownerUrl: https://afu.so.ch
          servicer: https://agi.so.ch
          technicalContact: mailto:agi@bd.so.ch
          #furtherInformation: http://geo.so.ch/models/AGI/SO_AGI_AV_GB_Administrative_Einteilungen_Publikation_20180822.uml
          #furtherMetadata: https://www.geocat.ch/geonetwork/srv/ger/md.viewer#/full_view/c899f44f-7c8b-89b5-3c27-617cc9fdfa56
          #knownWMS: 'https://geo.so.ch/api/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.so.agi.av.fixpunkte&STYLES=&SRS=EPSG%3A2056&CRS=EPSG%3A2056&TILED=false&DPI=96&OPACITIES=255&t=633&WIDTH=1544&HEIGHT=907&BBOX=2576618.3333333335%2C1214252.2916666667%2C2658321.6666666665%2C1262247.708333333'
          fileFormats:
            - xtf
            - gpkg
            - shp
            - dxf
        - id: ch.so.afu.ekat2015
          version: current
          owner: mailto:afu@bd.so.ch
          model: SO_AFU_Ekat_Publikation_20190222
          #epsgCode: 2056
          #resolutionScope: 500
          #publishingDate: 2020-08-29
          #lastEditingDate: 2020-08-29
          title: Emissionskataster 2015
          shortDescription: 
          keywords: Ekat,Emissionskataster,AFU
          provider: Amt für Umwelt
          ownerUrl: https://afu.so.ch
          servicer: https://agi.so.ch
          technicalContact: mailto:agi@bd.so.ch
          #furtherInformation: http://geo.so.ch/models/AGI/SO_AGI_AV_GB_Administrative_Einteilungen_Publikation_20180822.uml
          #furtherMetadata: https://www.geocat.ch/geonetwork/srv/ger/md.viewer#/full_view/c899f44f-7c8b-89b5-3c27-617cc9fdfa56
          #knownWMS: 'https://geo.so.ch/api/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.so.agi.av.fixpunkte&STYLES=&SRS=EPSG%3A2056&CRS=EPSG%3A2056&TILED=false&DPI=96&OPACITIES=255&t=633&WIDTH=1544&HEIGHT=907&BBOX=2576618.3333333335%2C1214252.2916666667%2C2658321.6666666665%2C1262247.708333333'
          fileFormats:
            - xtf
            - gpkg
            - shp
            - dxf
        - id: ch.so.afu.erdwaermesonden
          version: current
          owner: mailto:afu@bd.so.ch
          model: SO_AFU_Ekat_Publikation_20190222
          #epsgCode: 2056
          #resolutionScope: 500
          #publishingDate: 2020-08-29
          #lastEditingDate: 2020-08-29
          title: Erdwärmesonden
          shortDescription: 
          keywords: EWS,Erdwärmesonden,AFU
          provider: Amt für Umwelt
          ownerUrl: https://afu.so.ch
          servicer: https://agi.so.ch
          technicalContact: mailto:agi@bd.so.ch
          #furtherInformation: http://geo.so.ch/models/AGI/SO_AGI_AV_GB_Administrative_Einteilungen_Publikation_20180822.uml
          #furtherMetadata: https://www.geocat.ch/geonetwork/srv/ger/md.viewer#/full_view/c899f44f-7c8b-89b5-3c27-617cc9fdfa56
          #knownWMS: 'https://geo.so.ch/api/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.so.agi.av.fixpunkte&STYLES=&SRS=EPSG%3A2056&CRS=EPSG%3A2056&TILED=false&DPI=96&OPACITIES=255&t=633&WIDTH=1544&HEIGHT=907&BBOX=2576618.3333333335%2C1214252.2916666667%2C2658321.6666666665%2C1262247.708333333'
          fileFormats:
            - xtf
            - gpkg
            - shp
            - dxf
        - id: ch.so.afu.fischwanderhindernisse
          version: current
          owner: mailto:afu@bd.so.ch
          model: SO_AFU_Fischwanderhindernisse_Publikation_20220630
          #epsgCode: 2056
          #resolutionScope: 500
          #publishingDate: 2020-08-29
          #lastEditingDate: 2020-08-29
          title: Fischwanderhindernisse
          shortDescription: 
          keywords: Fischwanderhindernisse,Hindernisse,AFU
          provider: Amt für Umwelt
          ownerUrl: https://afu.so.ch
          servicer: https://agi.so.ch
          technicalContact: mailto:agi@bd.so.ch
          #furtherInformation: http://geo.so.ch/models/AGI/SO_AGI_AV_GB_Administrative_Einteilungen_Publikation_20180822.uml
          #furtherMetadata: https://www.geocat.ch/geonetwork/srv/ger/md.viewer#/full_view/c899f44f-7c8b-89b5-3c27-617cc9fdfa56
          #knownWMS: 'https://geo.so.ch/api/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.so.agi.av.fixpunkte&STYLES=&SRS=EPSG%3A2056&CRS=EPSG%3A2056&TILED=false&DPI=96&OPACITIES=255&t=633&WIDTH=1544&HEIGHT=907&BBOX=2576618.3333333335%2C1214252.2916666667%2C2658321.6666666665%2C1262247.708333333'
          fileFormats:
            - xtf
            - gpkg
            - shp
            - dxf
        - id: ch.so.afu.gefahrenkartierung
          version: current
          owner: mailto:afu@bd.so.ch
          model: SO_AfU_Gefahrenkartierung_20181129
          #epsgCode: 2056
          #resolutionScope: 500
          #publishingDate: 2020-08-29
          #lastEditingDate: 2020-08-29
          title: Gefahrenkartierung
          shortDescription: 
          keywords: Gefahrenkartierung,Naturgefahren,AFU
          provider: Amt für Umwelt
          ownerUrl: https://afu.so.ch
          servicer: https://agi.so.ch
          technicalContact: mailto:agi@bd.so.ch
          #furtherInformation: http://geo.so.ch/models/AGI/SO_AGI_AV_GB_Administrative_Einteilungen_Publikation_20180822.uml
          #furtherMetadata: https://www.geocat.ch/geonetwork/srv/ger/md.viewer#/full_view/c899f44f-7c8b-89b5-3c27-617cc9fdfa56
          #knownWMS: 'https://geo.so.ch/api/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.so.agi.av.fixpunkte&STYLES=&SRS=EPSG%3A2056&CRS=EPSG%3A2056&TILED=false&DPI=96&OPACITIES=255&t=633&WIDTH=1544&HEIGHT=907&BBOX=2576618.3333333335%2C1214252.2916666667%2C2658321.6666666665%2C1262247.708333333'
          fileFormats:
            - xtf
            - gpkg
            - shp
            - dxf
        - id: ch.so.afu.geotope
          version: current
          owner: mailto:afu@bd.so.ch
          model: SO_AFU_Geotope_Publikation_20200623
          #epsgCode: 2056
          #resolutionScope: 500
          #publishingDate: 2020-08-29
          #lastEditingDate: 2020-08-29
          title: Geotope / Ingeso (Inventar der geowissenschaftlich schützenswerten Objekte)
          shortDescription: 
          keywords: Geotope,Ingeso,AFU
          provider: Amt für Umwelt
          ownerUrl: https://afu.so.ch
          servicer: https://agi.so.ch
          technicalContact: mailto:agi@bd.so.ch
          #furtherInformation: http://geo.so.ch/models/AGI/SO_AGI_AV_GB_Administrative_Einteilungen_Publikation_20180822.uml
          #furtherMetadata: https://www.geocat.ch/geonetwork/srv/ger/md.viewer#/full_view/c899f44f-7c8b-89b5-3c27-617cc9fdfa56
          #knownWMS: 'https://geo.so.ch/api/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.so.agi.av.fixpunkte&STYLES=&SRS=EPSG%3A2056&CRS=EPSG%3A2056&TILED=false&DPI=96&OPACITIES=255&t=633&WIDTH=1544&HEIGHT=907&BBOX=2576618.3333333335%2C1214252.2916666667%2C2658321.6666666665%2C1262247.708333333'
          fileFormats:
            - xtf
            - gpkg
            - shp
            - dxf
        - id: ch.so.agi.lidar
          version: current
          owner: mailto:agi@bd.so.ch
          model: 
          #epsgCode: 2056
          #resolutionScope: 500
          #publishingDate: 2020-08-29
          #lastEditingDate: 2020-08-29
          title: LiDAR (Rohdaten, Höhenmodelle & Höhenkurven)
          shortDescription: 
          keywords: LiDAR,Laserscanning,DTM,Schattenbild,Hillshading,Terrain,AGI
          provider: Amt für Geoinformation (AGI)
          ownerUrl: https://agi.so.ch
          servicer: https://agi.so.ch
          technicalContact: mailto:agi@bd.so.ch
          #furtherInformation: http://geo.so.ch/models/AGI/SO_AGI_Lidarprodukte_Publikation_20180202.uml
          #furtherMetadata: https://www.geocat.ch/geonetwork/srv/ger/md.viewer#/full_view/c899f44f-7c8b-89b5-3c27-617cc9fdfa56
          #knownWMS: 'https://geo.so.ch/api/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.so.agi.av.fixpunkte&STYLES=&SRS=EPSG%3A2056&CRS=EPSG%3A2056&TILED=false&DPI=96&OPACITIES=255&t=633&WIDTH=1544&HEIGHT=907&BBOX=2576618.3333333335%2C1214252.2916666667%2C2658321.6666666665%2C1262247.708333333'
          subunits: 'https://geo.so.ch/map/?k=3bf6fee30'
          fileFormats:
            - gtiff
        - id: ch.so.agi.orthofoto
          version: current
          owner: mailto:agi@bd.so.ch
          model: 
          #epsgCode: 2056
          #resolutionScope: 500
          #publishingDate: 2020-08-29
          #lastEditingDate: 2020-08-29
          title: Historische Orthofotos
          shortDescription: 
          keywords: Orthofoto,Luftbild,RGB,CIR,AGI
          provider: Amt für Geoinformation (AGI)
          ownerUrl: https://agi.so.ch
          servicer: https://agi.so.ch
          technicalContact: mailto:agi@bd.so.ch
          #furtherInformation: http://geo.so.ch/models/AGI/SO_AGI_Lidarprodukte_Publikation_20180202.uml
          #furtherMetadata: https://www.geocat.ch/geonetwork/srv/ger/md.viewer#/full_view/c899f44f-7c8b-89b5-3c27-617cc9fdfa56
          #knownWMS: 'https://geo.so.ch/api/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=ch.so.agi.av.fixpunkte&STYLES=&SRS=EPSG%3A2056&CRS=EPSG%3A2056&TILED=false&DPI=96&OPACITIES=255&t=633&WIDTH=1544&HEIGHT=907&BBOX=2576618.3333333335%2C1214252.2916666667%2C2658321.6666666665%2C1262247.708333333'
          subunits: 'https://geo.so.ch/geodata/'
          fileFormats:
            - gtiff
